"""Add valid column

Revision ID: 9229f126ea4d
Revises: 1bd2940d9dc4
Create Date: 2026-01-26 14:09:24.608507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9229f126ea4d'
down_revision: Union[str, Sequence[str], None] = '1bd2940d9dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_accounts', sa.Column('valid', sa.Boolean(), nullable=False))
    op.alter_column('instagram_accounts', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_accounts', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('instagram_accounts', 'valid')
    # ### end Alembic commands ###
